config/routes.rb
Rails.application.routes.draw do
  
  resource :session, only: %i(create destroy)
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  resources :movies, only: %i(new create destroy) do
    resource :vote, only: %i(create destroy)
  end

  resources :users, only: %i() do
    resources :filter, only: %i() do
      resources :movies, only: %(index), controller: 'movies'
    end
  end

  root 'movies#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return if user.nil?

    can :vote, Movie do |movie|
      movie.user_id != user.id
    end

    can :create, Movie
  end
end

app/models/base_model.rb
require 'ohm'
require 'ohm/contrib'

class BaseModel < Ohm::Model
  def to_param
    id
  end
end

app/models/movie.rb
class Movie < BaseModel
  include Ohm::Timestamps

  attribute :title
  attribute :date
  attribute :description

  reference :user, :User

  attribute :liker_count
  attribute :hater_count

  set :likers, :User
  set :haters, :User
end

app/models/user.rb
class User < BaseModel
  include Ohm::Timestamps

  attribute :name

  # Unique identifier for this user, in the form "{provider}|{provider-id}"
  attribute :uid
  index     :uid
  unique    :uid

  # Session token
  attribute :token
  index     :token

  # Submitted movies
  collection :movies, :Movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authenticate!(user)
    token = SecureRandom.hex
    user.update(token: token)
    session[:token] = token
    @current_user = user
  end

  def logout!
    current_user.update(token: nil) if current_user
    session[:token] = nil
    @current_user = nil
  end

  helper_method :current_user

  def current_user
    @current_user ||= begin
      return unless token = session[:token]
      user = User.find(token: token).first
      return unless user
      UserDecorator.new(user)
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @user_id = _index_params[:user_id] || MovieSearch::ALL
    @filter = _index_params[:filter_id] || MovieSearch::ALL
    @movies = MovieSearch.new(
      scope: Movie.all, creator_id: @user_id,
      current_user: current_user, sort: _index_params[:by], filter: @filter
    ).call
  end

  def new
    authorize! :create, Movie

    @movie = Movie.new
    @validator = NullValidator.instance
  end

  def create
    authorize! :create, Movie

    attrs = _create_params.merge(user: current_user)
    @movie = Movie.new(attrs)
    @validator = MovieValidator.new(@movie)

    if @validator.valid?
      @movie.save
      flash[:notice] = "Movie added"
      redirect_to root_url
    else
      flash[:error] = "Errors were detected"
      render 'new'
    end
  end

  private

  def _index_params
    params.permit(:by, :user_id, :filter_id)
  end

  def _create_params
    params.permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def create
    UserRegistration.new(auth_hash).tap do |ur|
      authenticate! ur.user

      if ur.created?
        flash[:notice] = "Account created"
      else
        flash[:notice] = "Welcome back"
      end
    end
    redirect_to root_url
  end

  def destroy
    logout!
    redirect_to root_url
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    authorize! :vote, _movie

    _voter.vote(_type)
    redirect_to root_path, notice: 'Vote cast'
  end

  def destroy
    authorize! :vote, _movie

    _voter.unvote
    redirect_to root_path, notice: 'Vote withdrawn'
  end

  private

  def _voter
    VotingBooth.new(current_user, _movie)
  end

  def _type
    case params.require(:t)
    when 'like' then :like
    when 'hate' then :hate
    else raise
    end
  end

  def _movie
    @_movie ||= Movie[params[:movie_id]]
  end
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title MovieRama
    %meta{ 'http-equiv' => 'content-type', content: "text/html;charset=UTF-8" }/
    %meta{ charset: 'utf-8' }/
    %meta{ name: 'viewport',  content: "width=device-width, initial-scale=1.0" }/
    %link{ rel: 'stylesheet', type: 'text/css', href: 'https://fonts.googleapis.com/css?family=Roboto+Slab:300,700' }/

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{ role: 'navigation' }
      .container
        .navbar-header
          %a.navbar-brand{ href: root_path } MovieRama
        - if current_user
          %p.navbar-text.navbar-right
            Welcome back,
            %span#username= current_user.name
            = link_to session_path, method: :delete do
              Log out
        - else
          %a.navbar-right.btn.navbar-btn{ href: '/auth/github' }
            Log in
          %a.navbar-right.btn.navbar-btn{ href: '/auth/github' }
            Sign up

    .container
      .row
        .col-md-12
          - flash.each do |name, message|
            .alert.alert-info.mr-flash{class: "flash-#{name}"}= message

    = yield

app/views/movies/index.haml
.container
  .row
    .col-md-12
      .page-header
        - if @submitter
          %h2
            Movies
            %small submitted by #{@submitter.name}
        - else
          %h2 Movies
  - if current_user
    .row.mr-filter
      .col-md-12
        .well.well-sm
          Filter by
          = link_to('my_liked', user_filter_movies_path(@user_id, "my_liked"))
          |
          = link_to('my_hated', user_filter_movies_path(@user_id, "my_hated"))
          |
          = link_to('all', user_filter_movies_path(@user_id, MovieSearch::ALL))

  .row.mr-sorter
    .col-md-12
      .well.well-sm
        Sort by
        = link_to('likers', by: 'likers')
        |
        = link_to('haters', by: 'haters')
        |
        = link_to('date', by: 'date')

  .row
    .col-md-9
      - @movies.each do |movie|
        - movie = MovieDecorator.new(movie)
        .mr-movie.panel.panel-default
          .panel-heading
            %h4.mr-movie-title= movie.title
          .panel-body
            %p
              Posted by
              = link_to movie.user.name, user_filter_movies_path(movie.user.id, MovieSearch::ALL)
              = time_ago_in_words(movie.created_at)
              ago
            %p.mr-movie-description= movie.description
            %p.mr-release-date
              Released
              = movie.date
          .panel-footer
            .mr-movie-votes.pull-left
              - if movie.has_votes?
                = pluralize(movie.count_likers, 'like')
                |
                = pluralize(movie.count_haters, 'hate')
              - elsif can?(:vote, movie)
                Be the first to vote for this movie
              - else
                No votes yet
            - if current_user && can?(:vote, movie)
              .mr-movie-voting.pull-right
                - if current_user.likes?(movie)
                  You like this movie 
                  = link_to movie_vote_path(movie), method: :delete do
                    Unlike
                - elsif current_user.hates?(movie)
                  You hate this movie 
                  = link_to movie_vote_path(movie), method: :delete do
                    Unhate
                - else
                  = link_to movie_vote_path(movie, t:'like'), method: :post do
                    Like
                  |
                  = link_to movie_vote_path(movie, t:'hate'), method: :post do
                    Hate
            .clearfix
    .col-md-3
      - if can? :create, Movie
        .btn-group.btn-group-justified
          %a.btn.btn-primary{ href: new_movie_path }
            Add movie

app/views/movies/new.haml
.container
  .row
    .col-md-12
      .page-header
        %h2 Submit a movie
  .row
    .col-md-9
      = form_tag movies_path, { class: 'form', role: 'form' } do
        .form-group{ class: @validator.class_for(:title) }
          %label{ for:  'title' } Title
          %input.form-control{ name: 'title', value: @movie.title  }
        .form-group{ class: @validator.class_for(:description) }
          %label{ for: 'description' } Description
          %textarea.form-control{ name: 'description' }
            = @movie.description
        .form-group{ class: @validator.class_for(:date) }
          %label{ for:  'date' } Date
          %input.form-control{ name: 'date', type: 'date', value: @movie.date }
        .form-group
          = submit_tag 'Add movie', class: 'btn btn-primary'
       